### ISSUE TITLE
New script not working for me

### ISSUE THREAD

**Issue by lawhazl** [ahmanwoods/Oculus-Defibrillator#2]
Hi, thanks for your work on the update, unfortunately its not working for me, this is the result. 
I have the oculus app open and signed into my facebook account

Heartbeat failed with status code: 400 and response: {"error":{"message":"Failed to decrypt: facebook::fbcrypto::CryptoException: Padded data size is not a multiple of block size","type":"OAuthException","code":190,"fbtrace_id":

**Comment by ahmanwoods** [comment]
Could you add me on Discord? I need some more info about what's going on.

Nero#4210

**Comment by ahmanwoods** [comment]
This has been resolved in https://github.com/ahmanwoods/Oculus-Defibrillator/commit/96f65482517371b5cefa64dea6fc587cafd63d3f. It appears that tokens can vary slightly in length depending on if the account is Facebook only or still has a base Oculus account connected.
