### ISSUE TITLE
Heartbeat Failed with status code: 400

### ISSUE THREAD

**Issue by Toaster-X3** [ahmanwoods/Oculus-Defibrillator#5]
I reinstalled windows recently and reinstalled Revive and Oculus and copied over the defibrillator from my previous install, and I keep getting this.
Heartbeat FAILED with status code: 400 and response: {"error":{"message":"Invalid OAuth 2.0 Access Token","type":"OCApiException","code":190,"error_data":{},"fbtrace_id":"AsGc50sqKtirbt54-OE-fVg"}}
I have installed requests, and everything is exactly as it was in the previous install of windows. I tried downloading the latest version, and the latest version just doesn't even start. It flashes on screen then goes away immediately.

**Comment by Nekcik** [comment]
I'm having the same error when I do it as well.

**Comment by ahmanwoods** [comment]
@ToasterCorporation @Nekcik

Can you both try the update I just put up?

**Comment by Toaster-X3** [comment]
I forgot this thread existed, for an unknown reason it started working again for me after a little while
